languageCode = "en-us"
baseurl = "http://learntla.com"
title = "Learn TLA"
theme = "hugo-theme-learn"
PygmentsCodeFences = true

[Params]
  Author = "Hillel Wayne"
  menu = ["introduction", "pluscal", "tla", "models", "concurrency", "temporal-logic"]
